build prof

diff --git a/CUJExecutor/manipulateProfilesAndTest b/CUJExecutor/manipulateProfilesAndTest
--- a/CUJExecutor/manipulateProfilesAndTest
+++ b/CUJExecutor/manipulateProfilesAndTest
@@ -19,38 +19,37 @@
 # Compiles aGMM according to the COMPILATION_FLAG and then measures the CUJ specified by the INPUT_FILE (as specified by executeCUJ).
 # Stores the following files at /profile_test_data/<INPUT_FILE_NAME>/<COMPILATION_FLAG>/<DATE>/:
 # - (command_summary.txt) a log of each run command and their output.
-# - (short_summary.txt) a formatted summary including the profile used for compilation, resulting app size and measurements of the MEASURED_CUJ (acquired via a call to executeCUJ). A copy is stored in /tmp for the callee.
+# - (short_summary.txt) a formatted summary including the profile used for compilation, resulting app size and measurements of the POST_CUJ (acquired via a call to executeCUJ). A copy is stored in /tmp for the callee.
 # - (saved_profile.prof) the profile used to compile the app (if applicable). 
 # - (median_clip.mp4) a recording of the median iteration (if requested).
 #
-# @param INPUT_FILE (Formatted with the following on consecutive lines: PRE-CUJ, MEASURED_CUJ, POST_CUJ, NUM_ITERS, and optionally RECORD (a line with an "r" to indicate that you'd like to record). See CUJS/ for an example file.
-# @param COMPILATION_FLAG (e - empty profile, m - compile measured CUJ, u - compile with a cloud profile, f- compile first action, p - compile actions in Pre-CUJ, c - compile pre and measured CUJS, a - compile all code).
-#  	 Optionally, if f, p, c, or m are followed by a number, n, (e.g. m12), that portion of the CUJ will be run through n times during the creation of the profile. If a, e or u are followed by a number, that number will be ignored.
+# @param INPUT_FILE (Formatted with the following on consecutive lines: PRE-CUJ, POST_CUJ, NUM_ITERS, and optionally RECORD (a line with an "r" to indicate that you'd like to record). See CUJS/ for an example file.
+# @param COMPILATION_FLAG (e - empty profile, p - compile actions in Pre-CUJ, c - compile entire CUJ, a - compile all code).
 
+# Example: ./manipulateProfilesAndTest CUJS/takeout.txt p
 # Result: Will reset the profile attempt to add actions in the pre-CUJ to it. Then re-compiles the app according to that profile and measures the CUJ specified by CUJS/takeout.txt.
 
 
 
 
 #PARSING INPUTS:
-INPUT_FILE=${1?"ERROR: need to specify an input file and compilation flag"}
-COMPILATION_FLAG=${2?"ERROR: need to specify an input file and compilation flag"} 
-#if [ $COMPILATION_FLAG != "e" ] && [ $COMPILATION_FLAG != "p" ] && [ $COMPILATION_FLAG != "c" ] && [ $COMPILATION_FLAG != "a" ] && [ $COMPILATION_FLAG != "f" ] && [ $COMPILATION_FLAG != "u" ] && [ $COMPILATION_FLAG != "m" ]  
-#then
-#	echo "compilation flag invalid. Use one of {e - empty profile, p - compile actions in Pre-CUJ, c - compile pre and measured CUJS, a - compile all code, f - compile first action, u - compile using cloud profile, m - compile only using the measured CUJ}"
-#	exit 1	
-#fi	
-
-echo $COMPILATION_FLAG
+INPUT_FILE=${1:-input.txt}
+COMPILATION_FLAG=${2?"ERROR: need to specify a compilation flag"} 
+if [ $COMPILATION_FLAG != "e" ] && [ $COMPILATION_FLAG != "p" ] && [ $COMPILATION_FLAG != "c" ] && [ $COMPILATION_FLAG != "a" ] 
+then
+	echo "compilation flag invalid. Use one of {e - empty profile, p - compile actions in Pre-CUJ, c - compile entire CUJ, a - compile all code}"
+	exit 1	
+fi	
 
 #Initializing variables
 INPUT_FILE_NAME="${INPUT_FILE##*/}"
 INPUT_FILE_NAME="${INPUT_FILE_NAME%.*}"
-RECORD=$(sed '5q;d' $INPUT_FILE)
+RECORD=$(sed '4q;d' $INPUT_FILE)
+TIME_DATA="/tmp/time_data.txt"
 
 #PREPARING OUTPUTS:
 DATE=$(date '+%m-%d-%Y--%H:%M:%S')
-HEADER_FOOTER="\n--------------------------------COMPILATION SETTING: ${COMPILATION_FLAG}----------${DATE}-------------------------------"
+HEADER_FOOTER="--------------------------------COMPILATION SETTING: ${COMPILATION_FLAG}----------${DATE}-------------------------------"
 #Generate the appropriate folder hierarchy if it doesn't already exist
 FOLDER="profile_test_data/${INPUT_FILE_NAME}"
 mkdir $FOLDER 2> /dev/null
@@ -58,23 +57,12 @@ FOLDER="profile_test_data/${INPUT_FILE_NAME}/${COMPILATION_FLAG}"
 mkdir $FOLDER 2> /dev/null
 FOLDER="profile_test_data/${INPUT_FILE_NAME}/${COMPILATION_FLAG}/${DATE}"
 mkdir $FOLDER 2> /dev/null
-CLOUD_PROFILE="utilityProfiles/cloudProfile.prof" #location of the saved cloud profile
-EMPTY_PROFILE="utilityProfiles/empty.prof" #location of an empty profile
-CUR_PROFILE="/data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof" #location of the cur profile on the device
-REF_PROFILE="/data/misc/profiles/ref/com.google.android.apps.maps/primary.prof" #location of the ref profile on the device
-STASHED_SUMMARY_TABLE="/tmp/execute_summary_table.txt"
-STASHED_CREATED_PROFILE="/tmp/build_created_profile.txt"
-STASHING_APP_SIZE="/tmp/manipulate_app_size.txt" #Contains final app size in case callee (e.g. mega_test) wants it
-STASHING_USED_PROFILE="/tmp/manipulate_created_profile.txt" #Contains the profile used to compile
-STASHING_COMPILED_ACTIONS="/tmp/manipulate_compiled_actions.txt" #Contains the actions used to compile, in case callee (e.g. mega_test) wants it
-STASHING_FOLDER="/tmp/manipulate_folder.txt" #Contains the name of the folder where files for this test live in case callee (e.e. mega_test) wants it
+APP_SIZE_DATA="/tmp/app_size.txt" #Contains final app size in case callee (e.g. mega_test) wants it
 COMMAND_SUMMARY="${FOLDER}/command_summary.txt" #contains full summary commands and raw outputs
 SHORT_SUMMARY="${FOLDER}/short_summary.txt" #contains short summary of time data and size of profile/app
-STASHING_SHORT_SUMMARY="/tmp/manipulate_short_summary.txt" #copy of short summary in case callee (e.g. mega_test) wants it
+TMP_SHORT_SUMMARY="/tmp/short_summary.txt" #copy of short summary in case callee (e.g. mega_test) wants it
 SAVED_PROFILE="${FOLDER}/saved_profile.prof" #contains short summary of time data and size of profile/app
 MEDIAN_CLIP="${FOLDER}/median_clip.mp4" #contains a clip of the median run if one is requested
-FULL_CLIP="${FOLDER}/full_video.mp4" #contains a clip of the full run if one is requested
-
 echo "" > $COMMAND_SUMMARY
 
 #spit command output to Full_Summary and echo it
@@ -90,58 +78,56 @@ function spitToFull() {
 }
 
 
-#Add header for data
-echo -e $HEADER_FOOTER > $SHORT_SUMMARY
+#ADD HEADER FOR DATA
+echo $HEADER_FOOTER > $SHORT_SUMMARY
 echo "SIZE DATA:" >> $SHORT_SUMMARY
 echo "" >> $SHORT_SUMMARY
 
+echo "Resetting the profile...."
+output=$(spitToFull "adb shell cmd package compile --reset com.google.android.apps.maps")
 
+#Get the desired actions into the profile:
+if [ "$COMPILATION_FLAG" = "c" ] || [ "$COMPILATION_FLAG" = "p" ] 
+then
+	
+	echo "Adding the desired actions to the profile..."
+	output=$(spitToFull "./runCujNTimes $INPUT_FILE $COMPILATION_FLAG 1")
 
-
-
-
-if [ "$COMPILATION_FLAG" = "a" ] 
-then 
-	echo "All" > $STASHING_COMPILED_ACTIONS
+	echo "Waiting..."
+	output=$(spitToFull "sleep 60")
 
 	echo "Force stopping Maps..."
 	output=$(spitToFull "adb shell am force-stop com.google.android.apps.maps")
 	
+
+	echo "Saving the profile..."
+	output=$(spitToFull "adb pull /data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof $SAVED_PROFILE")
+
+	echo "Getting profile size..."
+	output=$(spitToFull "adb shell ls -l /data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof")
+	PROFILE_SIZE=$(adb shell stat -c%s /data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof)
+	echo "Size of profile: $PROFILE_SIZE" >> $SHORT_SUMMARY
+	
+	echo "Recompiling profile..."
+	output=$(spitToFull "adb shell cmd package compile -m speed-profile -f com.google.android.apps.maps")
+
+elif [ "$COMPILATION_FLAG" = "a" ] 
+then 
 	echo "Compiling everything..."
 	output=$(spitToFull "adb shell cmd package compile -m everything -f com.google.android.apps.maps")
 
-else 	#default case is to attempt to build the profile
-	echo "Building the profile..."
-	output=$(spitToFull "./buildProfile $INPUT_FILE $COMPILATION_FLAG")
-	
-	echo "Force stopping Maps..."
-	output=$(spitToFull "adb shell am force-stop com.google.android.apps.maps")
-
-	echo "Pushing the created profile..."
-	output=$(spitToFull "adb push $STASHED_CREATED_PROFILE $CUR_PROFILE")
-
-	echo "Restoring profile permissions"
-	output=$(spitToFull "adb shell chmod a+rw $CUR_PROFILE")
-	
-	echo "Saving the profile..."
-	output=$(spitToFull "adb pull $CUR_PROFILE $SAVED_PROFILE")
-	
-	echo "Recompiling profile..."  
-	output=$(spitToFull "adb shell cmd package compile -m speed-profile -f com.google.android.apps.maps")
-
+elif [ "$COMPILATION_FLAG" = "e" ]
+then
 	echo "Getting profile size..."
-	PROFILE_SIZE=$(spitToFull "adb shell stat -c%s $REF_PROFILE")
+	output=$(spitToFull "adb shell ls -l /data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof")
+	PROFILE_SIZE=$(adb shell stat -c%s /data/misc/profiles/cur/0/com.google.android.apps.maps/primary.prof)
 	echo "Size of profile: $PROFILE_SIZE" >> $SHORT_SUMMARY
 fi
 
-
-echo "Force stopping Maps..."
-output=$(spitToFull "adb shell am force-stop com.google.android.apps.maps")
-
-echo "Getting app size..." 
+echo "Getting app size..." #IS THIS "total" value the proper APP SIZE???
 output=$(spitToFull "adb shell ls -l /data/app/com.google.android.apps.maps*/oat/arm64")
 APP_SIZE=$(echo $output | awk '{print $2}')
-echo $APP_SIZE > $STASHING_APP_SIZE
+echo $APP_SIZE > $APP_SIZE_DATA
 
 echo "Size of app: $APP_SIZE" >> $SHORT_SUMMARY
 echo "" >> $SHORT_SUMMARY
@@ -151,24 +137,14 @@ echo "Executing and measuring the CUJ..."
 output=$(spitToFull "./executeCuj $INPUT_FILE")
 
 #Prepare short summary
-cat $STASHED_SUMMARY_TABLE >> $SHORT_SUMMARY
-echo -e $HEADER_FOOTER >> $SHORT_SUMMARY
-cat $SHORT_SUMMARY > $STASHING_SHORT_SUMMARY
-echo "$FOLDER" > "$STASHING_FOLDER"
+cat $TIME_DATA >> $SHORT_SUMMARY
+echo $HEADER_FOOTER >> $SHORT_SUMMARY
+cat $SHORT_SUMMARY > $TMP_SHORT_SUMMARY
 
 if [ "$RECORD" = "r" ] && [ -f "median_clip.mp4" ]
 then 
 	mv median_clip.mp4 $MEDIAN_CLIP
-	echo "Path to median video: $MEDIAN_CLIP"
-fi
-
-if [ "$RECORD" = "f" ] || [ "$RECORD" = "r" ]
-then 
-	if  [ -f "full_video.mp4" ]
-	then 
-		mv full_video.mp4 $FULL_CLIP
-		echo "Path to full video: $FULL_CLIP"
-	fi
+	echo "output video is called: $MEDIAN_CLIP"
 fi
 
 cat $SHORT_SUMMARY
