updates + fileToDump

diff --git a/CUJExecutor/profileToDump b/CUJExecutor/profileToDump
--- a/CUJExecutor/profileToDump
+++ b/CUJExecutor/profileToDump
@@ -8,7 +8,7 @@ PACKAGE=${2:-com.google.android.apps.maps}
 
 if [ ! -f "$PROFILE" ]  || [ "${PROFILE##*.}" != "prof" ]
 then
-        >&2 echo "ERROR: provided profile is not a valid .prof file"
+        >&2 echo "ERROR: provided profile: "$PROFILE" is not a valid .prof file"
         exit 1
 fi
 
